text.exe:Convertor.o JSON_checker.o validationJson.o xJ_Convertor.o main.o
		gcc  Convertor.o JSON_checker.o validationJson.o xJ_Convertor.o main.o text.exe
Convertor.o:Convertor.c XJ_Convertor.h
		gcc -c Convertor.c
JSON_checker.o:JSON_checker.c JSON_checker.h
		gcc -c JSON_checker.c
validationJson.o:validationJson.c JSON_checker.h
		gcc	-c validationJson.c
xJ_Convertor.o:xJ_Convertor.c xJ_Convertor.h
		gcc -c xJ_Convertor.c
main.o:main.c JSON_checker.h
		gcc -c main.c
							